public class ContactsManager {
    int friendCount;
    Contact [] friends;

    //Constructor for when user wants to specify
    ContactsManager(int friendCount, Contact [] friends){
        this.friendCount = friendCount;
        this.friends = friends;
    }

    //Want to specify our own default constructor instead of using Java's autogenerated because want to initiate friends to specific length
    ContactsManager(){
        this.friendCount = 0;
        this.friends = new Contact[500];
    }

    //methods to manipulate data
    void addFriend(Contact contact){
        friends[friendCount] = contact;
        friendCount++;
    }

    Contact searchFriend(String searchName){
        for (int i = 0; i < friendCount; i++){
            if (friends[i].name.equals(searchName)) {
                return friends[i];
            }
        }
        return null;
    }
}
